# Site settings
title: The ELEMIS Spa Collection
client:
  name: ELEMIS
  link: https://click.linksynergy.com/deeplink?id=rg1rVdkt0EQ&mid=42744&murl=https%3A%2F%2Fwww.elemis.com%2F
core-se-link: https://www.secretescapes.com/current-sales
description: >
  You deserve to be pampered. Let the restorative treatments at our gorgeous spa escapes refresh and revitalise mind, body and soul, a perfect treat, just for you, over the winter season. We’ve hand-picked the finest spa getaways in Britain, set for days of endless relaxation in sumptuous surroundings.

discount-tandcs: "*20% off purchase discount code and accompanying T&C's – Code : SEVIP20 T&Cs: Not valid on ULTRA SMART Pro-Collagen products, gift vouchers, collections or sale items. Subject to availability. Offers ends 30 April 2020. One use per customer only. Cannot be combined with any other offer or code."
house-of-elemis-tandcs: "*Terms and conditions apply. 20% off on full length treatments only when customer quotes “Secret Escapes“. Offer ends on 31st March."

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/elemis" # the subpath of your site, e.g. /blog/
img:     "/elemis/_assets/img"
css:     "/elemis/_assets/css"
js:      "/elemis/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed