# Site settings
title: The ELEMIS Spa Collection
client:
  name: ELEMIS
  link: https://www.elemis.com/
core-se-link: https://www.secretescapes.com/current-sales
description: >
  You deserve a pampering. Let the restorative treatments at our gorgeous spa escapes refresh and revitalise mind, body and soul, a perfect treat, just for you, over the winter season. We’ve hand-picked the finest spa getaways in Britain, set for days of endless relaxation in sumptuous surroundings. With exclusive offers from ELEMIS, upgrade your spa break and treat yourself to products and treatments from Britain’s no.1 luxury skincare company. Discover the House of ELEMIS for luxurious treatments in the heart of London’s exclusive Mayfair plus an extra gift for Secret Escapes members, and browse the exceptional skincare range – because we all deserve a pampering once in a while...

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/elemis" # the subpath of your site, e.g. /blog/
img:     "/elemis/_assets/img"
css:     "/elemis/_assets/css"
js:      "/elemis/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed