# Site settings
title: The ELEMIS Spa Collection
client:
  name: ELEMIS
  link: https://www.elemis.com/
core-se-link: https://www.secretescapes.com/current-sales
description: >
  You deserve to be pampered. Let the restorative treatments at our gorgeous spa escapes refresh and revitalise mind, body and soul, a perfect treat, just for you, over the winter season. We’ve hand-picked the finest spa getaways in Britain, set for days of endless relaxation in sumptuous surroundings.

discount-tandcs: "*20% off purchase discount code and accompanying T&C's – Code : SEVIP20 T&Cs: Not valid on ULTRA SMART Pro-Collagen products, gift vouchers, collections or sale items. Subject to availability. Offers ends 30 April 2020. One use per customer only. Cannot be combined with any other offer or code."

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/elemis" # the subpath of your site, e.g. /blog/
img:     "/elemis/_assets/img"
css:     "/elemis/_assets/css"
js:      "/elemis/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed